{% set name = "micawber" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc04c19a5e0eb3615b8cd95d5aefdad5cde4f52a61c12d45071727dfe131b760

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - micawber
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coleifer/micawber/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a small library for extracting rich content from urls

extra:
  recipe-maintainers:
    - mands
