{% set name = "micawber" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ac5814b65ff2a781fb1394b91a23a8a95f73492b6bb8f705baeead82eadd543

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - micawber
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coleifer/micawber/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a small library for extracting rich content from urls

extra:
  recipe-maintainers:
    - mands
