{% set name = "micawber" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f98fb914d1b33b626e3aae6734e268650321428dd7af02e42c2a78efc203b7b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - micawber
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coleifer/micawber/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a small library for extracting rich content from urls

extra:
  recipe-maintainers:
    - mands
